Retry

diff --git a/.githooks/check b/.githooks/check
--- a/.githooks/check
+++ b/.githooks/check
@@ -1,8 +1,4 @@
-#!/bin/env bash
-
-set -e
-set -u
-set -o pipefail
+#!/bin/sh
 
 dir="$(dirname "$0")"
 
@@ -17,7 +13,7 @@ parallel_3 () {
   "$dir/test_rust"
 
   cd rust
-  cargo +stable test
+  cargo +stable test || { echo "FAIL RUST STABLE"; exit 1; }
   cd ..
 }
 
diff --git a/.githooks/test_kotlin b/.githooks/test_kotlin
--- a/.githooks/test_kotlin
+++ b/.githooks/test_kotlin
@@ -1,16 +1,12 @@
-#!/bin/env bash
-
-set -e
-set -u
-set -o pipefail
+#!/bin/sh
 
 dir="$(dirname "$0")"
 
-ktlint
+ktlint || { echo "FAIL KTLINT"; exit 1; }
 
 cd "$dir/../kotlin/"
 
-gradle clean
-gradle test
+gradle clean || { echo "FAIL"; exit 1; }
+gradle test || { echo "FAIL KOTLIN"; exit 1; }
 
 cd -
diff --git a/.githooks/test_python b/.githooks/test_python
--- a/.githooks/test_python
+++ b/.githooks/test_python
@@ -1,14 +1,10 @@
-#!/bin/env bash
-
-set -e
-set -u
-set -o pipefail
+#!/bin/sh
 
 dir="$(dirname "$0")"
 
 cd "$dir/../"
 
-black --check python
-pytest
+black --check python || { echo "FAIL BLACK"; exit 1; }
+pytest || { echo "FAIL PYTHON"; exit 1; }
 
 cd -
diff --git a/.githooks/test_rust b/.githooks/test_rust
--- a/.githooks/test_rust
+++ b/.githooks/test_rust
@@ -1,15 +1,11 @@
-#!/bin/env bash
-
-set -e
-set -u
-set -o pipefail
+#!/bin/sh
 
 dir="$(dirname "$0")"
 
 cd "$dir/../rust/"
 
-cargo test
-cargo fmt --check
-cargo clippy --no-deps -- -D warnings
+cargo test || { echo "FAIL RUST"; exit 1; }
+cargo fmt --check || { echo "FAIL FMT"; exit 1; }
+cargo clippy --no-deps -- -D warnings || { echo "FAIL CLIPPY"; exit 1; }
 
 cd -
diff --git a/.githooks/test_schema b/.githooks/test_schema
--- a/.githooks/test_schema
+++ b/.githooks/test_schema
@@ -1,9 +1,5 @@
-#!/bin/env bash
-
-set -e
-set -u
-set -o pipefail
+#!/bin/sh
 
 dir="$(dirname "$0")"
 
-python "$dir/../data/test_spec.py"
+python "$dir/../data/test_spec.py" || { echo "FAIL SCHEMA"; exit 1; }
